services:
  app:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - .:/node/app:delegated
      - /node/app/node_modules
