version: '3.9'
services:
  client:
    build:
      context: ./TourVR_FE
      dockerfile: Dockerfile.dev
    volumes:
      - ./TourVR_FE:/app
      - ./TourVR_FE/pages:/app/pages
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:1612
    networks:
      - tourvr
  api:
    build:
      context: ./TourVR_BE
      dockerfile: Dockerfile.dev
    volumes:
      - ./TourVR_BE:/app
      - ./TourVR_BE/src:/app/src
    environment:
      - PORT=1612
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    networks:
      - tourvr

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - api
    ports:
      - '1000:80'
    networks:
      - tourvr

networks:
  tourvr:
