# Multi-Stage
# Stage 1: build
FROM node:16-alpine as build

WORKDIR /app

COPY . .

RUN yarn && yarn build

# Stage 2: prod
FROM node:16-alpine as prod

WORKDIR /app

RUN chown -R node:node /app

USER node

COPY --chown=node:node --from=build /app/dist /app/dist

COPY --chown=node:node --from=build /app/package.json /app/

COPY --chown=node:node --from=build /app/yarn.lock /app/

RUN yarn install --only=prod

CMD [ "yarn", "start:prod" ]